# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches:
      - master
  release:
    types: [published]

permissions:
  contents: read

jobs:  

#  build-linux:
#    name: Build linux Python wheels
#    runs-on: ubuntu-latest

#    steps:
#     - name: Checkout
#       uses: actions/checkout@v4

#      - name: Build manylinux Python wheels
#        uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64
#        with:
#          python-versions: 'cp36-cp36m cp37-cp37m'

#      - uses: actions/upload-artifact@master
#        with:
#          name: linux-wheels
#          path: dist/*-manylinux*.whl

#  run-tests:
#    name: Test interface
#    needs: [build-linux]
#    runs-on: ubuntu-22.04
    
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v4

#      - uses: actions/download-artifact@master
#        with:
#          name: linux-wheels
#          path: dist

#      - name: Install Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'

#      - name: Install dependencies
#        run: |
#          pip install pip@git+https://github.com/jsego/unified-planning
#          pip install -r requirements.txt
#          pip install -e .
          
#      - name: Run basic test 
#        run: |
#          cd tests/
#          python test_up_bfgp.py

  deploy:
    runs-on: ubuntu-latest
    #needs: [run-tests]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
#        pip install pip@git+https://github.com/jsego/unified-planning
        pip install -r requirements.txt
        pip install build
        
    - name: Build package
      run: python -m build
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
